### PR TITLE
Implement wasi-http serving.

### PR DESCRIPTION
**Pull request by brendandburns**
cc @achille-roussel 

This implements HTTP serving in the `wasi-http` specification. It enables `wasi-run` to act as an HTTP server for web assembly.

Let me know if you'd prefer that this was in a different binary.

There are C and [Go](https://github.com/dev-wasm/dev-wasm-go/blob/main/http/server.go) examples.

### CODE REVIEW

**Review by achille-roussel — APPROVED** [review]
The change looks good, thanks for adding tests!

I'm OK with adding options on wasirun to exercise the features supported in this package 👍 

I'm curious about the new `types` module that this PR introduces, do you know if it is described somewhere a specification, or is there another runtime implementing it?

**Comment by brendandburns** [comment]
The `types` module is defined in this WIT file:

https://github.com/WebAssembly/wasi-http/blob/main/wit/types.wit

Note that the fact that it is called `types` is actually due to a bug in the [`wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen) tool which didn't use namespaces correctly.

When we revise this forward to be a `v2` the name of this module will move to 
`wasi::http::`

**Comment by brendandburns** [comment]
Just for context, there is an intersection between the `wit` files, the `wit-bindgen` tool and the guest SDK that is used to access the functionality.

**Comment by achille-roussel** [comment]
Thanks for the explanations!

**Pull request merged**
